POST http://localhost:3000/category HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGRiN2QwNWUzMjlmNDM2ZTkyYWUwZiIsInVzZXJuYW1lIjoicGlwZVVzZXI1IiwiaWF0IjoxNjg3MDk5MTI3LCJleHAiOjE2ODcxMDI3Mjd9.uMjPwZ_W0PWvvA78A3GMJrWpoFXEGfDs5ky1H8kmk-c

    {
      "name": "Bebida"
    }
