GET http://localhost:3000/category
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGRiN2QwNWUzMjlmNDM2ZTkyYWUwZiIsInVzZXJuYW1lIjoicGlwZVVzZXI1IiwiaWF0IjoxNjg3MDE0MjE1LCJleHAiOjE2ODcwMTc4MTV9.n2P23dlWoGbNtaZAR9DzDEkRgJJ38OkKWpCyhkAPQ4o