GET http://localhost:3000/movements
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGRiN2QwNWUzMjlmNDM2ZTkyYWUwZiIsInVzZXJuYW1lIjoicGlwZVVzZXI1IiwiaWF0IjoxNjg3MDM3NDk1LCJleHAiOjE2ODcwNDEwOTV9.a0BNqWQ72ykswKUYrznsfiIkI0oUFhmsCt8NXbyZ8Gw
