GET http://localhost:3000/movements/month?month=3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGRiN2QwNWUzMjlmNDM2ZTkyYWUwZiIsInVzZXJuYW1lIjoicGlwZVVzZXI1IiwiaWF0IjoxNjg3MzUwODM3LCJleHAiOjE2ODczNTQ0Mzd9.hwGi6zK7ZhFpBh08VhoaIRSiZYgapN3rlkofkbHncRA
